/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f407xx.h"

void delay(){
	for(uint32_t i=0;i<500000;i++);
}

int main(void)
{
   GPIO_Handle_t gpioLed, gpioButton;

   gpioLed.pGPIOx=GPIOD;
   gpioLed.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_12;
   gpioLed.GPIO_PinConfig.GPIO_PinMode=GPIO_MODE_OUT;
   gpioLed.GPIO_PinConfig.GPIO_PinSpeed=GPIO_SPEED_FAST;
   gpioLed.GPIO_PinConfig.GPIO_PinOPType=GPIO_OP_TYPE_PP;
   gpioLed.GPIO_PinConfig.GPIO_PinPuPdControl=GPIO_NO_PUPD;

   GPIO_PeriClockControl(GPIOD,ENABLE);
   GPIO_Init(&gpioLed);

   gpioButton.pGPIOx=GPIOB;
   gpioButton.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_12;
   gpioButton.GPIO_PinConfig.GPIO_PinMode=GPIO_MODE_IN;
   gpioButton.GPIO_PinConfig.GPIO_PinSpeed=GPIO_SPEED_FAST;
   gpioButton.GPIO_PinConfig.GPIO_PinPuPdControl=GPIO_NO_PUPD;

   GPIO_PeriClockControl(GPIOB,ENABLE);
   GPIO_Init(&gpioButton);


   while(1){
	   if(GPIO_ReadFromInputPin(GPIOB,GPIO_PIN_NO_12)==0){
		   delay();
		   GPIO_ToggleOutputPin(GPIOD,GPIO_PIN_NO_12);
	   }
   }

}
